# Generated by Django 3.1.4 on 2020-12-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='comment',
            field=models.CharField(default=1, max_length=300, verbose_name='Вопрос'),
            preserve_default=False,
        ),
    ]
